import json
import os
import re

# Paths
API_DUMP_PATH = 'aa/api_dump.json'
OUTPUT_DIR = 'aa/prompts'

# Ensure output directory exists
os.makedirs(OUTPUT_DIR, exist_ok=True)

def sanitize_filename(name):
    """Sanitize the title for a safe filename."""
    return re.sub(r'[<>:"/\\|?*]', '', name).strip().replace(' ', '_')

def extract_video_url(text):
    """Attempt to extract the first video URL from the prompt text if any."""
    urls = re.findall(r'https?://[^\s\"\']+\.(?:mp4|webm|m3u8)', text)
    return urls[0] if urls else None

# Load data
with open(API_DUMP_PATH, 'r') as f:
    data = json.load(f)

prompts = data.get('prompts', [])
print(f"Generating {len(prompts)} README files...")

for i, p in enumerate(prompts):
    title = p.get('title', f"Prompt_{i}")
    prompt_text = p.get('prompt_text', '')
    category = p.get('category', 'N/A')
    p_type = p.get('type', 'N/A')
    is_free = p.get('is_free', False)
    
    # Try to find a video URL
    video_url = extract_video_url(prompt_text)
    
    # Create Markdown content
    md_content = f"""# {title}

> **Category:** {category}  
> **Type:** {p_type}  
> **License:** {'Free' if is_free else 'Premium'}

---

## 🎬 Video Preview

"""
    
    if video_url:
        md_content += f"""<video width="100%" controls autoplay muted loop>
  <source src="{video_url}" type="video/mp4">
  Your browser does not support the video tag.
</video>

[Direct Video Link]({video_url})

"""
    else:
        md_content += "_No video preview available for this prompt._\n\n"

    md_content += f"""---

## 📋 Prompt

```text
{prompt_text}
```

---

*Generated by MotionSites Export Tool*
"""
    
    # Write to file
    safe_filename = sanitize_filename(title) + '.md'
    file_path = os.path.join(OUTPUT_DIR, safe_filename)
    
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(md_content)

print(f"\n--- SUCCESS: {len(prompts)} README files generated in {OUTPUT_DIR} ---")
